name: Reusable Workflow

on:
  workflow_call:
    inputs:
      node:
        required: true
        type: string

jobs:
  call_reuseable_workflow:
    strategy:
      matrix:
        nodeversion: [14, 16, 18, 20]
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      node: ${{ matrix.nodeversion }}
      
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Output the input value
        run: |
          echo "The node version to use is: ${{ inputs.node }}"
